-- =============================================================================
-- HelperHub Backend Migration Script (Supabase)
-- =============================================================================

-- 1. SETUP EXTENSIONS
create extension if not exists "pgcrypto";
create extension if not exists "postgis" with schema "extensions";

-- 2. ENUMS & CONSTANTS (Managed via CHECK constraints as requested)

-- 3. TABLES

-- PROFILES: Linked to Supabase Auth
create table if not exists public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  email text,
  full_name text,
  phone_number text,
  avatar_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.profiles enable row level security;

-- SERVICES: Catalog of available services
create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  base_price numeric(10,2) not null check (base_price >= 0),
  image_url text,
  is_active boolean default true,
  created_at timestamptz default now()
);
alter table public.services enable row level security;

-- WORKERS_PUBLIC: Public profile data for workers (queryable by users)
create table if not exists public.workers_public (
  id uuid default gen_random_uuid() primary key,
  full_name text not null,
  profile_image_url text,
  service_types text[], -- Array of service names/ids they perform
  rating numeric(3,2) default 5.0 check (rating >= 1 and rating <= 5),
  total_reviews int default 0,
  hourly_rate numeric(10,2),
  location geography(Point, 4326), -- Geospatial location
  is_verified boolean default false,
  bio text,
  created_at timestamptz default now()
);
alter table public.workers_public enable row level security;

-- ADDRESSES: User saved addresses
create table if not exists public.addresses (
  id uuid default gen_random_uuid() primary key,
  customer_id uuid references public.profiles(id) on delete cascade not null,
  label text, -- e.g., "Home", "Office"
  address_line1 text not null,
  address_line2 text,
  city text,
  postal_code text,
  location geography(Point, 4326),
  created_at timestamptz default now()
);
alter table public.addresses enable row level security;

-- BOOKINGS: Core booking capability
create table if not exists public.bookings (
  id uuid default gen_random_uuid() primary key,
  customer_id uuid references public.profiles(id) not null,
  worker_id uuid references public.workers_public(id), -- Nullable if not yet matched
  service_id bigint references public.services(id) not null,
  address_id uuid references public.addresses(id),
  status text not null check (status in ('requested', 'matched', 'accepted', 'en_route', 'in_progress', 'completed', 'paid', 'cancelled')) default 'requested',
  scheduled_at timestamptz not null,
  duration_minutes int check (duration_minutes > 0),
  total_amount numeric(10,2) check (total_amount >= 0),
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.bookings enable row level security;

-- TRANSACTIONS: Payment records
create table if not exists public.transactions (
  id uuid default gen_random_uuid() primary key,
  booking_id uuid references public.bookings(id) not null,
  amount numeric(10,2) not null check (amount >= 0),
  payment_method text check (payment_method in ('upi', 'card', 'cash', 'netbanking')),
  status text check (status in ('pending', 'success', 'failed', 'refunded')),
  provider_transaction_id text,
  created_at timestamptz default now()
);
alter table public.transactions enable row level security;

-- REVIEWS: Post-service feedback
create table if not exists public.reviews (
  id uuid default gen_random_uuid() primary key,
  booking_id uuid references public.bookings(id) unique not null,
  reviewer_id uuid references public.profiles(id) not null, -- Customer
  worker_id uuid references public.workers_public(id) not null,
  rating int not null check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamptz default now()
);
alter table public.reviews enable row level security;

-- NOTIFICATIONS: User alerts
create table if not exists public.notifications (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) not null,
  title text not null,
  message text not null,
  is_read boolean default false,
  metadata jsonb,
  created_at timestamptz default now()
);
alter table public.notifications enable row level security;


-- 4. INDICES
create index if not exists idx_workers_location on public.workers_public using gist (location);
create index if not exists idx_workers_rating on public.workers_public (rating desc);
create index if not exists idx_bookings_customer on public.bookings (customer_id);
create index if not exists idx_bookings_worker on public.bookings (worker_id);
create index if not exists idx_bookings_status on public.bookings (status);
create index if not exists idx_bookings_scheduled on public.bookings (scheduled_at);
create index if not exists idx_addresses_location on public.addresses using gist (location);


-- 5. RLS POLICIES

-- Profiles: Users see their own. Admins/Service Role see all (implicit).
create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- Services: Public read-only
create policy "Public can view active services" on public.services for select using (is_active = true);

-- Workers Public: Public read-only (Authenticated users only)
create policy "Auth users can view workers" on public.workers_public for select to authenticated using (true);

-- Addresses: Private to user
create policy "Users see own addresses" on public.addresses for select using (auth.uid() = customer_id);
create policy "Users insert own addresses" on public.addresses for insert with check (auth.uid() = customer_id);
create policy "Users update own addresses" on public.addresses for update using (auth.uid() = customer_id);
create policy "Users delete own addresses" on public.addresses for delete using (auth.uid() = customer_id);

-- Bookings: Private to user
create policy "Users see own bookings" on public.bookings for select using (auth.uid() = customer_id);
create policy "Users insert own bookings" on public.bookings for insert with check (auth.uid() = customer_id);
-- Note: Updates to bookings (e.g. status changes) usually handled by worker or system RPC, 
-- but users might cancel.
create policy "Users can cancel requested bookings" on public.bookings for update using (auth.uid() = customer_id and status = 'requested');

-- Transactions: Private to user (read-only for user, created by system)
create policy "Users see own transactions" on public.transactions for select 
using (exists (select 1 from public.bookings b where b.id = transactions.booking_id and b.customer_id = auth.uid()));

-- Reviews: Viewable by all (for worker ratings), creatable by customer of booking
create policy "Public view reviews" on public.reviews for select to authenticated using (true);
create policy "Users create reviews for own bookings" on public.reviews for insert with check (
  auth.uid() = reviewer_id and 
  exists (select 1 from public.bookings b where b.id = booking_id and b.customer_id = auth.uid())
);

-- Notifications: Private
create policy "Users see own notifications" on public.notifications for select using (auth.uid() = user_id);
create policy "Users update own notifications" on public.notifications for update using (auth.uid() = user_id); -- e.g. mark as read


-- 6. RPC FUNCTIONS

-- rpc_nearby_workers: Find workers near a location
create or replace function nearby_workers(
  lat double precision,
  lng double precision,
  service_filter text default null,
  radius_meters int default 10000
)
returns table (
  id uuid,
  full_name text,
  rating numeric,
  hourly_rate numeric,
  dist_meters float,
  is_verified boolean,
  profile_image_url text
)
language sql
security definer -- Used to access worker data cleanly, though RLS allows select.
as $$
  select
    id,
    full_name,
    rating,
    hourly_rate,
    st_distance(location, st_point(lng, lat)::geography) as dist_meters,
    is_verified,
    profile_image_url
  from
    public.workers_public
  where
    st_dwithin(location, st_point(lng, lat)::geography, radius_meters)
    and (service_filter is null or service_types @> array[service_filter])
  order by
    dist_meters asc;
$$;

-- rpc_create_booking: Atomic booking creation stub
create or replace function create_booking(
  customer_uuid uuid,
  service_id_input bigint,
  address_id_input uuid,
  scheduled_at_input timestamptz,
  duration_minutes_input int,
  preferred_worker_id_input uuid default null
)
returns uuid
language plpgsql
security definer -- Runs with elevated privileges to ensure data consistency
as $$
declare
  new_booking_id uuid;
  service_price numeric;
  service_location geography(Point, 4326);
begin
  -- 1. Security Check: Ensure caller manages this user (or is admin)
  if auth.uid() <> customer_uuid then
    raise exception 'Unauthorized: User ID mismatch';
  end if;

  -- 2. Validation & Pricing Lookup
  select base_price into service_price from public.services where id = service_id_input limit 1;
  if not found then raise exception 'Service not found'; end if;

  -- 2b. Location Lookup (Spatial Bridge)
  if address_id_input is not null then
    select location into service_location from public.addresses where id = address_id_input limit 1;
  end if;

  -- 3. Insert Booking
  insert into public.bookings (
    customer_id,
    service_id,
    address_id,
    worker_id,
    scheduled_at,
    duration_minutes,
    total_amount,
    location,
    status
  ) values (
    customer_uuid,
    service_id_input,
    address_id_input,
    preferred_worker_id_input,
    scheduled_at_input,
    duration_minutes_input,
    -- Simple pricing logic: base * (duration/60), minimal example
    round((service_price * (duration_minutes_input::numeric / 60.0)), 2),
    service_location,
    'requested'
  )
  returning id into new_booking_id;

  -- 4. Note: Push notification logic or worker assignment triggers would happen here (e.g. via Edge Function)

  return new_booking_id;
end;
$$;


-- 7. SEED DATA (For Testing)

-- Services
insert into public.services (name, description, base_price, image_url) values
('Everyday Cleaning', 'Standard home sweeping and mopping', 200.00, '/assets/cleaning.jpg'),
('Laundry', 'Washing, drying and folding per hour', 150.00, '/assets/laundry.jpg'),
('Expert Cook', 'Home style cooking for families', 300.00, '/assets/cook.jpg');

-- Workers (Coordinates around Mumbai - 19.0760, 72.8777)
insert into public.workers_public (full_name, service_types, hourly_rate, location, bio, is_verified) values
('Ramesh Kumar', ARRAY['Everyday Cleaning', 'Laundry'], 250.00, st_point(72.8777, 19.0760)::geography, 'Experienced reliable helper', true),
('Sunita Devi', ARRAY['Expert Cook', 'Everyday Cleaning'], 350.00, st_point(72.8800, 19.0800)::geography, 'Specializes in North Indian cuisine', true);

-- note: coordinates are (lng, lat) for st_point


-- =============================================================================
-- 8. VERIFICATION STEPS (Manual Test Comments)
-- =============================================================================
/*
TEST 1: RLS on Bookings
  -- Run as Authenticated User (simulate in Supabase SQL editor by assuming role):
  -- set role authenticated;
  -- select * from bookings; -- Should return empty or only own bookings
  -- insert into bookings (customer_id, service_id, scheduled_at) values ('CURRENT_USER_ID', 1, now()); -- Should succeed if ID matches

TEST 2: Nearby Workers RPC
  -- select * from nearby_workers(19.0760, 72.8777, null, 5000); 
  -- Should return Ramesh and Sunita ordered by distance

TEST 3: Create Booking RPC
  -- select create_booking('YOUR_AUTH_ID', 1, null, now() + interval '1 day', 120);
  -- Check table: select * from bookings where customer_id = 'YOUR_AUTH_ID';
*/
